name: Main

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable

    - name: Setup GLFW dependencies
      run: sudo apt install xorg-dev --yes

    - name: Setup haxe
      uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: 4.1.1

    - name: Setup haxe dependencies
      run: |
        haxelib install dox
        haxelib install hxcpp

    - name: Test samples
      run: |
        git clone https://github.com/ibilon/hxwgpu-samples.git --recursive
        cd hxwgpu-samples/libs/hxwgpu
        git pull https://github.com/ibilon/hxwgpu.git
        cd ../..
        haxe cppia_host.hxml
        haxe build_all.hxml

    - name: Deploy documentation
      run: |
        haxe cppia_host.hxml -xml documentation/hxwgpu.xml -D no-compilation
        haxelib run dox -o documentation/out/ -i documentation/hxwgpu.xml -in wgpu --title "hxwgpu API reference" --toplevel-package wgpu --keep-field-order -D version 0.0.1 -D source-path https://github.com/ibilon/hxwgpu/blob/master/ -D website https://github.com/ibilon/hxwgpu -D description "hxwgpu is a work in progress Haxe/hxcpp wrapper around wgpu-native, allowing the use of the WebGPU API on desktop"
        cd documentation/out
        git init
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ibilon/hxwgpu
        git checkout -b gh-pages
        git add -A .
        git commit -m "Deploying documentation"
        git push -u origin gh-pages --force
